### ISSUE TITLE
Generic git repo support

### ISSUE THREAD

**Issue by ivosabev** [lerna/lerna-changelog#44] opened 2017-03-17 12:45 UTC
Any plans of making the "repo" param take a generic git url, rather than a GH repo name.

For example:
```
"repo": "git@bitbucket.org:owner/repo.git"
```

**Comment by Turbo87** [comment] 2018-06-17 00:06
@ivosabev I'm closing this as a duplicate of #3 and #23 as they already propose similar things. Since we have to query the GitHub API for the label information and stuff like that it's unfortunately a little more complicated than just switching the repo URL.

**Closed by Turbo87** 2018-06-17 00:06 UTC
Labels: enhancement
